canonical/charmed-kubeflow-uats

- tests/notebooks/kserve-integration.ipynb
Introduce notebook to test KServe Integration:
* create an Inference Service
* perform inference
**This only works with `Serverless` deployment mode at the moment**, see the following issue for more:
* https://github.com/canonical/kserve-operators/issues/148
In order to switch to `Serverless` (see [here](https://github.com/canonical/kserve-operators#deploy-in-serverless-mode) for more):
* update the `kserve-controller` config:
```bash
juju config kserve-controller deployment-mode="serverless"
```
* relate `kserve-controller` to `knative-serving`:
```bash
juju relate kserve-controller:local-gateway knative-serving:local-gateway
```
Even with KServe deployed in `Serverless` mode, we still have the bug described in the following issue:
* …
> feat: Add KServe Integration notebook

- tests/notebooks/e2e-wine/.gitignore
- tests/notebooks/e2e-wine/e2e-wine-kfp-mlflow-seldon.ipynb
Introduce notebook that combines KFP, MLFlow, and Seldon to:
* download a dataset
* clean / preprocess data
* perform training / hyper-parameter tuning with MLFlow (+ MinIO)
* serve with Seldon
* perform inference
This PR relies on the fix introduced here: https://github.com/canonical/mlflow-operator/pull/183
The `mlflow-seldon-rclone-secret` Secret can be edited directly though (and the names updated to the correct ones) if the fix is not in place.
> feat: Add E2E Wine test notebook

- tests/notebooks/training-integration.ipynb
Introduce Notebook to test training operator integration
- create training job of type: TFJob, PyTorchJob, and PaddleJob
- monitor its execution
- get training logs
- delete job
Test Training Operator Integration
This example notebook is loosely based on [this](https://github.com/kubeflow/training-operator/blob/master/sdk/python/examples/kubeflow-tfjob-sdk.ipynb) upstream example.
<details><summary>Test run summary with pytest-operator</summary>
<p>
tox -e uats -- --filter "training"
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.4.0, pluggy-1.2.0 -- /opt/conda/bin/python3.8
cachedir: .pytest_cache
rootdir: /tests
configfile: pytest.ini
plugins: anyio-3.6.2
collecting ... collected 7 items / 6 deselected / 1 …
> feat: add training operator notebook tests

- .github/workflows/on_pull_or_push.yaml
Add a Github CI workflow to execute the configured linting checks on pull requests and when pushing against the `main` or `track/*` branches.
This is expected to fail until https://github.com/canonical/charmed-kubeflow-uats/pull/21 is merged.
Closes #22
> feat: Add CI workflow for linting

- tests/notebooks/e2e-wine/requirements.in
- tests/notebooks/e2e-wine/requirements.txt
- tests/notebooks/minio/requirements.in
- tests/notebooks/minio/requirements.txt
- tests/notebooks/mlflow/requirements.in
- tests/notebooks/mlflow/requirements.txt
minio sdk 7.0 is a breaking release that deprecates `BucketAlreadyOwnedByYou` and `BucketAlreadyExists` errors that we are using in the UATs. See issue https://github.com/minio/minio-py/issues/1051.
since we are using an old version of minio, it makes sense to pin the sdk to an older version.
> fix: pin minio<7.0

- tests/notebooks/kserve/kserve-integration.ipynb
- closes https://github.com/canonical/kserve-operators/issues/182
- clears the output of the kserve test notebook
> fix: kserve prediction url

- tests/notebooks/kserve/kserve-integration.ipynb
Add note that UAT notebook is only compatible with serverless deployment mode at the moment.
This note is also present in the notebook's PR https://github.com/canonical/charmed-kubeflow-uats/pull/10.
Closes https://github.com/canonical/charmed-kubeflow-uats/issues/47
> kserve-integration: Add `serveless` compatibility note

- driver/test_kubeflow_workloads.py
- driver/utils.py
- requirements.in
- requirements.txt
The addition of `trust_env=False` to lightkube allows the tests' kubernetes calls to ignore the proxy env variables and ping directly internal addresses. The rationale is explained in detail in https://github.com/canonical/charmed-kubeflow-uats/issues/27.
- Initialise lightkube with `trust_env=False` 
- Unpin juju since CKF latest/edge can be deployed in Juju 3.1
Refs #27
> fix: Initialise lightkube with `trust_env=False`

- tests/notebooks/katib/katib-integration.ipynb
This PR updates the katib example to include changes to the [upstream example](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb) we based this test on.  These changes were needed because the previous version requires a docker container that no longer exists.
Closes #64
I deployed a subset of Charmed Kubeflow using:
```
juju deploy istio-gateway --config kind=ingress --channel latest/edge --trust istio-ingressgateway
juju deploy istio-pilot --channel latest/edge --config default-gateway=kubeflow-gateway --trust
juju relate istio-pilot istio-ingressgateway
juju deploy kubeflow-roles --channel 1.8/stable --trust
juju deploy kubeflow-profiles --channel latest/edge --trust
juju deploy kubeflow-dashboard --channel latest/edge --trust
juju relate …
```
> update katib-integration.ipynb to use a new katib experiment

- README.md
- assets/test-job.yaml.j2
- driver/conftest.py
- driver/test_kubeflow_workloads.py
- driver/utils.py
- tox.ini
This PR fixes #65. Implemented solution is described in https://github.com/canonical/charmed-kubeflow-uats/issues/65#issuecomment-2016884170. It essentially add the option of running tests either from:
* a remote branch of `charmed-kubeflow-uats` repository.
* the local copy of the repository.
Closes #65
In order to test this, one needs to:
1. Deploy CKF in a microk8s environment and run `tox -e kubeflow-local`.
2. Deploy [CKF to an AKS](https://charmed-kubeflow.io/docs/deploy-charmed-kubeflow-to-aks)/[EKS cluster](https://charmed-kubeflow.io/docs/deploy-charmed-kubeflow-to-eks) and run `tox -e kubeflow-remote -- --branch kf-5473-add-remote-option`.
That being said, I 've tested option 2 in an AKS cluster only (it works) and it will be tested also by the CI once it is implemented in …
> feat: Run UATs from a remote commit

- tests/notebooks/training/training-integration.ipynb
As the updated notebook description mentions, 
* Update PyTorchJob image according to [upstream E2E tests](https://github.com/kubeflow/training-operator/blob/964a6e836eedff11edfe79cc9f4e5b7c623cbe88/sdk/python/test/e2e/test_e2e_pytorchjob.py#L267). The only difference is that we use `v1-3a360ba` (the most [recently pushed image](https://hub.docker.com/r/kubeflow/pytorch-dist-mnist/tags?page=&page_size=&name=&ordering=last_updated)) to avoid using `latest`, since this can result in inconsistent test runs. 
* Update registry from which PaddleJob image is pulled to follow [upstream E2E tests](https://github.com/kubeflow/training-operator/blob/964a6e836eedff11edfe79cc9f4e5b7c623cbe88/sdk/python/test/e2e/test_e2e_paddlejob.py#L158).
Closes canonical/bundle-kubeflow#894, …
> fix: training-integration uat by updating image

- tests/notebooks/training/training-integration.ipynb
Update the image to use one from katib repository, which is [2.75GB](https://hub.docker.com/layers/kubeflowkatib/pytorch-mnist-cpu/v1beta1-57ed828/images/sha256-27ba519167619c42f6810238e3c911f0d8e309f2204021dab96bd9df65e4b280?context=explore) instead of 10GB that the previous one was. The new image is being built from this [Dockerfile](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu),
Closes #69
> training-operator test: Update image

- tests/notebooks/katib/katib-integration.ipynb
Increase experiment's batch-size in order for the experiment to perform less training and thus complete earlier. 
The UAT's role is to confirm that the controller works, rather than run a full experiment training. (more details about debugging in the issue)
Fixes canonical/katib-operators#211
In order to test, deploy CKF `1.9/beta` to a Microk8s 1.29 and Juju 3.4. However, in order to perform a proper test of this you 'll need to rebase this branch (or cherry-pick the one commit) over the PR https://github.com/canonical/charmed-kubeflow-uats/pull/92 branch in order to have the new requirements as well. If done so, run
```
tox -e kubeflow-local -- --filter "katib"
```
> fix(katib): Increase experiment batch-size

- driver/test_kubeflow_workloads.py
- tests/notebooks/e2e-wine/requirements.in
- tests/notebooks/e2e-wine/requirements.txt
- tests/notebooks/katib/requirements.in
- tests/notebooks/katib/requirements.txt
- tests/notebooks/kserve/requirements.in
- tests/notebooks/kserve/requirements.txt
- tests/notebooks/mlflow-kserve/requirements.in
- tests/notebooks/mlflow-kserve/requirements.txt
Closes #73.
This PR updates the scipy image and the dependencies for all UATs in order to be compatible with CKF 1.9. 
- We are using the stable version `kubeflownotebookswg/jupyter-scipy:v1.9.0`
- `kubeflow-training` has been pinned to version `1.6.0` because of a breaking change in imports, as documented in #84
> Update scipy image and requirements for Charmed Kubeflow 1.9

- tests/notebooks/mlflow-kserve/requirements.in
- tests/notebooks/mlflow-kserve/requirements.txt
- tests/notebooks/mlflow-minio/requirements.txt
- tests/notebooks/mlflow/requirements.in
- tests/notebooks/mlflow/requirements.txt
Fix requirements to pin for mlflow 2.15.1
Fix kserve sdk to 0.13.1 to fix pydantic error on imports.
Manually tested on AWS instance
> Update requirements in MLflow's UATs

- README.md
Removing note as it is not needed anymore.
> docs: remove tfjob note as canonical/training-operator#182 is fixed

- README.md
part of #75 
Based on the bug fix for https://github.com/canonical/knative-operators/issues/204, it is required to set the proxy configs in `kserve-controller` and `knative-serving` charms before running the UATs behind proxy.
> readme: Add to proxy instructions the KServe and Knative proxy configs

- README.md
- tests/notebooks/kfp_v2/kfp-v2-integration.ipynb
- tests/proxy-poddefault.yaml.j2
Closes #109
Closes #110
For context, see https://github.com/canonical/charmed-kubeflow-uats/issues/109#issuecomment-2317578876 and https://github.com/canonical/charmed-kubeflow-uats/issues/110#issuecomment-2317635925
> Update `no_proxy` values to include `.kubeflow`

- driver/test_kubeflow_workloads.py
- driver/utils.py
Closes https://github.com/canonical/bundle-kubeflow/issues/951
* In the `create_profile` fixture, set the `cascade` to foreground to ensure all the child resources for the profile are deleted
* Remove the `delete_job` function, this is no longer needed since we are deleting all of the profile's namespace
> fix: refactor the `create_profile` fixture to ensure deletion

- driver/test_kubeflow_workloads.py
- driver/utils.py
closes https://github.com/canonical/bundle-kubeflow/issues/1066
This is to overcome the race condition sometimes happening between:
1. the poddefaults being created in the test namespace
2. the job being created in the test namespace
The extra wait ensures that `1` happens before `2`
* Adds a `sleep` after creating the namespace to allow the resources to be synced to the namespace before the job runs
* Asserts that the list of poddefaults in the namespace is not empty
* Logs the names of poddefaults found in the namespace
* Asserts that the `access-ml-pipeline` poddefault exists in the namespace
<details>
<summary>UATs run logs from the PR</summary>
<br>
```
tox -e uats-remote -- --filter "not e2e"
uats-remote: commands[0]> pytest -vv --tb native /home/ubuntu/uat/driver/ -s --model …
```
> fix: wait to allow PodDefaults to synced in Job's namespace before running tests

- driver/test_kubeflow_workloads.py
- requirements.in
- requirements.txt
closes #121 
The PR uses [`pytest-dependency` plugin](https://pytest-dependency.readthedocs.io/en/latest/index.html) to define the dependencies between the tests. 
See https://github.com/canonical/charmed-kubeflow-uats/issues/121#issuecomment-2358217050 on why we went against using the `pytest-operator` marker `@pytest.mark.abort_on_fail`.
to make the `test_create_profile` fail, I  edited [L154](https://github.com/canonical/charmed-kubeflow-uats/blob/main/driver/test_kubeflow_workloads.py#L154) to be `assert profile_created==False, f"Profile {NAMESPACE} not found!"`
The result logs from running the UATs:
```
tox -e uats-remote -- --filter "kfp-v2"
uats-remote: commands[0]> pytest -vv --tb native /home/ubuntu/uat/driver/ -s --model kubeflow --filter kfp-v2 …
```
> fix: skip `test_kubeflow_workloads` when `test_create_profile` fails

- tests/notebooks/e2e-wine/e2e-wine-kfp-mlflow-kserve.ipynb
- tests/notebooks/kfp_v2/kfp-v2-integration.ipynb
Closes: https://github.com/canonical/bundle-kubeflow/issues/1067
Disables caching for kfp-v2 pipelines. All details are in the issue.
I have tested in one click deployment and also in my own microk8s deployment. 
After deploying kubeflow and mlflow I run:
```
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt update -y
sudo apt install python3.8 python3.8-distutils python3.8-venv -y
python3.8 -m venv venv
source venv/bin/activate
pip install tox
git clone https://github.com/canonical/charmed-kubeflow-uats.git
cd charmed-kubeflow-uats
tox -e uats-remote -- --keep-models -vv -s
```
> Disable caching for kfp-v2 pipelines in UATs

- tox.ini
Closes: https://github.com/canonical/mlflow-operator/issues/272
Adds tox environment for MLflow related UATs.
> Add tox for running MLflow UATs only

- driver/test_kubeflow_workloads.py
- requirements.in
- requirements.txt
Backports https://github.com/canonical/charmed-kubeflow-uats/pull/120 to `track/1.8`
Part of fixing https://github.com/canonical/charmed-kubeflow-uats/issues/142
**Summary**
The PR uses [pytest-dependency plugin](https://pytest-dependency.readthedocs.io/en/latest/index.html) to define the dependencies between the tests.
> fix: skip `test_kubeflow_workloads` when `test_create_profile` fails (#122)

- driver/test_kubeflow_workloads.py
- driver/utils.py
Backports https://github.com/canonical/charmed-kubeflow-uats/pull/120 to `track/1.8`
Part of fixing https://github.com/canonical/charmed-kubeflow-uats/issues/142
**Summary**
* fix: check PodDefaults in namespace before running tests
* sleep until resources are synced to namespace
* assert on kfp poddefault
* use tenacity to wait for kfp poddefault
* log on apierror to get poddefault
> fix: wait to allow PodDefaults to synced in Job's namespace before running tests (#120)

- driver/test_kubeflow_workloads.py
- driver/utils.py
Backports #117 to `track/1.8`
Part of fixing #142 
**Summary**
* fix: delete the Profile in the foreground
* assert profile deleted
> fix: refactor the `create_profile` fixture to ensure deletion (#117)

- tests/notebooks/cpu/kserve/kserve-integration.ipynb
Retry getting the ISVC URL since it failed intermitently why the ISVC had been created.
Fix canonical/bundle-kubeflow#1100
In order to run UATs from the branch, we 'd need to first merge #158. You can test this though from a branch that has KServe fix and the #158 fix (or removes the `test_bundle_correctness` check).
> fix(kserve): Retry getting the ISVC URL

- README.md
- driver/conftest.py
- driver/test_kubeflow_workloads.py
Fix #157
Addressing [KF-6902](https://warthogs.atlassian.net/browse/KF-6902)
[KF-6902]: https://warthogs.atlassian.net/browse/KF-6902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Some changes are required also in the bundle. [This PR](https://github.com/canonical/bundle-kubeflow/pull/1205) covers the modifications there.
> feat: Add bundle url as input and use latest as default

- README.md
Closes #167 
This PR updated the README.md to:
- Properly define the prerequisites for running the UATs using the drivers
- Declare support for Python >= 3.10 (as defined in `pyproject.toml`)
> Update README.md to show Python support for 3.10+

- README.md
- driver/conftest.py
Updating the `BUNDLE_URL` reference to point to the 1.10 stable bundle for the 1.10 releases
> chore: update reference to 1.10/stable bundle

- driver/test_kubeflow_workloads.py
In the TF deployment there is one charm that is in blocked status by design, which prevents the UATs to pass. This change only restrict the check for active/idle to the KF charms only. 
This change is meant to be backported also to:
* main
* track/1.9
> [KF-7085] chore: check active/idle only for bundle charms

- driver/test_kubeflow_workloads.py
Forward ports #177 to main
In the TF deployment there is one charm that is in blocked status by design, which prevents the UATs to pass. This change only restrict the check for active/idle to the KF charms only.
> [KF-7085] chore: check active/idle only for bundle charms (#177)
